name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Run only when you push a tag like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Needed for trusted publishing (optional)

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
